"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def whats_the_total():
    fib_sequence = []
    
    def fib_sum(n):
        if n == 1:
            return 1
        elif n == 2:
            return 2
        else:
            return (fib_sum(n-1) + fib_sum(n-2))
    
    total = 0
    i = 1
    while  fib_sum(i) < 4000000:
        if i % 2 == 0:
            total += fib_sum(i)
        i += 1
    
    return total

print(whats_the_total())

        